# Generated by Django 6.0.3 on 2026-03-31 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'dinosaur'. Used in API paths.", unique=True)),
                ('label', models.CharField(help_text="Display name, e.g. 'T-Rex'", max_length=64)),
                ('emoji', models.CharField(default='◉', max_length=8)),
                ('color', models.CharField(default='#2563eb', help_text='Accent colour for the scatter plot markers.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex colour, e.g. #2563eb')])),
                ('point_count', models.PositiveIntegerField(default=800, help_text='Number of scatter points to generate.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the UI.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive shapes are hidden from the UI and API.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shape',
                'verbose_name_plural': 'Shapes',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ShapePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'body', 'head', 'left_leg'", max_length=64)),
                ('part_type', models.CharField(choices=[('spline', 'Spline (smooth curve through points)'), ('scatter', 'Scatter (random noise around points)'), ('math', 'Parametric / mathematical (no control points needed)')], default='spline', max_length=10)),
                ('control_points', models.JSONField(default=list, help_text='List of [x, y] pairs defining the silhouette path.')),
                ('point_count', models.PositiveIntegerField(default=100, help_text='How many scatter points to generate from this part.')),
                ('noise_scale', models.FloatField(default=0.6, help_text='Standard deviation of Gaussian noise added to spline samples.')),
                ('flip_y', models.BooleanField(default=False, help_text='Negate Y after generation (useful to flip upside-down shapes).')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='scatter.shape')),
            ],
            options={
                'verbose_name': 'Shape part',
                'verbose_name_plural': 'Shape parts',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
