# Generated by Django 6.0.3 on 2026-04-01 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scatter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='point_count',
        ),
        migrations.AlterField(
            model_name='shape',
            name='color',
            field=models.CharField(default='#2563eb', help_text='Accent hex colour for scatter plot markers, e.g. #2563eb', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex colour.')]),
        ),
        migrations.AlterField(
            model_name='shape',
            name='slug',
            field=models.SlugField(help_text="URL-safe identifier used in API paths, e.g. 'dinosaur'.", unique=True),
        ),
        migrations.CreateModel(
            name='ShapePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='scatter.shape')),
            ],
            options={
                'verbose_name': 'Shape point',
                'verbose_name_plural': 'Shape points',
                'ordering': ['pk'],
            },
        ),
        migrations.DeleteModel(
            name='ShapePart',
        ),
    ]
