# Generated by Django 6.0.3 on 2026-04-01 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scatter', '0003_shape_points_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null = public predefined shape. Set to a user = private to that user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shape',
            name='color',
            field=models.CharField(default='#2563eb', help_text='Accent hex colour for scatter plot markers.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex colour.')]),
        ),
    ]
